dist: bionic

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.26.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - make init-dev-config
  - make run-detached

script:
  - sleep 200
  - make test-unit
  - make test-e2e

after_script:
  - make stop

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      # echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      # make build-image;
      # make push-image;
      echo "Branch ist master"
    fi
